README.md, src/Schema/Blueprint.php, tests/Functional/HasIndexTest.php
```php
Schema::table('some_table', function (Blueprint $table) {
// check unique index exists on column
if ($table->hasIndex(['column'], true)) {
$table->dropUnique(['column']);
}
$table->uniquePartial('column')->whereNull('deleted_at');
});
```
=> Add has index methods to facade

src/UmbrellioPostgresProvider.php
It may fix a bug with a connection error to the database after calling composer install.
=> Bug: Connection refused

.travis.yml, src/Helpers/ColumnAssertions.php, src/Helpers/IndexAssertions.php, src/Helpers/TableAssertions.php, src/Helpers/ViewAssertions.php, tests.sh, tests/Functional/Schema/CreateIndexTest.php, tests/Functional/Schema/CreateTableTest.php, tests/Functional/Schema/CreateViewTest.php
fix bug: cannot use trait ColumnAssertions  in other package.
=> Fix traits namespace

phpunit.xml.dist, src/PostgresConnection.php
Fixed using $pdo as \PDO type when it is Closure
=> fix: getPdo() instead $pdo

composer.json, composer.lock
add laravel version 7 in composer requirenments
=> Add laravel7 support in composer

.github/workflows/ci.yml, README.md, phpunit.github.xml
- Removed coverage badge by Scrutinizer
- Some fixes in ci.yml (with name artefacts)
- Some fixes in phpunit.xml for Github Actions
=> Fixed bugs in workflow checks

composer.json, composer.lock
- Added licence to composer
- Added suggest
- Testing Doctrine\Dbal ^3.0 with PHP 8.0 (maybe conflict)
=> Updated composer.json

.github/workflows/ci.yml, composer.json, composer.lock, phpunit.xml.dist, tests.sh, tests/Functional/Subscribers/ChangeColumnSubscriberTest.php
- Fixed tests for environment PHP 8.0
- Added support Doctrine\Dbal ^3.0
- Changed ci.yml for jobs with PHP 8.0
=> Resolved problems for PHP 8 & Doctrine\Dbal ^3.0

.github/release-drafter.yml, .github/workflows/auto_release.yml
Some changes in auto release workflow.
=> Maybe fixed error in auto release worker after merge PR's

.github/release-drafter.yml, .github/workflows/auto_release.yml
- Added changes to template for draft release.
- Added options for auto publish release.
=> Auto publish draft releases

src/PostgresConnection.php, src/Schema/Types/NumericType.php, src/Schema/Types/TsRangeType.php
=> Auto register supported types

tests/Unit/Schema/Types/NumericTypeTest.php, tests/Unit/Schema/Types/TsRangeTypeTest.php
=> Added tests for coverage

.github/auto_assign.yml, README.md, phpunit.xml.dist, tests.sh
- Updated readme
- Some fixes for local testing
- Migrate to new format for phpunit config
=> CI improvements

.github/labeler.yml, .github/release-drafter.yml, .github/workflows/ci.yml, README.md, composer.json, phpunit.xml.dist, src/.meta.php, src/Compilers/ExcludeCompiler.php, src/Compilers/UniqueCompiler.php, src/Helpers/ColumnAssertions.php, src/Helpers/IndexAssertions.php, src/Helpers/TableAssertions.php, src/Helpers/ViewAssertions.php, src/PostgresConnection.php, src/Schema/Blueprint.php, src/Schema/Builder.php, src/Schema/Builders/WhereBuilderTrait.php, src/Schema/Grammars/PostgresGrammar.php, src/Schema/Subscribers/SchemaAlterTableChangeColumnSubscriber.php, tests.sh
- Fixed major scrutinizer issues
- Updated readme
- Fixed issue with CI launch for other PR types
- Fixes for phpunit & composer
=> Scrutinizer fixes

.github/workflows/ci.yml, README.md
=> Опечатка доки в описании check констрейнта. 

src/.meta.php, src/Schema/Blueprint.php, src/Schema/Grammars/PostgresGrammar.php, src/Schema/Types/DateRangeType.php, tests.sh, tests/Unit/Schema/Blueprint/PartitionTest.php, tests/Unit/Schema/Types/DateRangeTypeTest.php
Added supporting daterange type in Laravel
=> Added supporting daterange type in Laravel

.github/workflows/ci.yml, composer.json, src/UmbrellioPostgresProvider.php
- Update dependencies
- Add missed db services bindings
=> Laravel 9 support

src/PostgresConnection.php, src/Schema/Blueprint.php, src/Schema/Grammars/PostgresGrammar.php, src/Schema/Types/TsTzRangeType.php, tests/Unit/Schema/Blueprint/PartitionTest.php, tests/Unit/Schema/Types/TsTzRangeTypeTest.php
There was a method for tsrange type, but none for tstzrange type, so I implemented it.
FYI
https://www.postgresql.org/docs/current/rangetypes.html
=> add tstzrange function

src/.meta.php
i'm sorry but i forgot to add `tstzrange()` method to `.meta.php`.
so i added it.
FYI #74
=> add tstzrange method to phpdoc in .meta.php

src/Schema/Builder.php
=> Fix compatibility with laravel/framework#49231

.github/workflows/ci.yml, composer.json
=> bump laravel version
